# Generated by Django 5.2.4 on 2025-07-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_husband_m_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='is_married',
            field=models.BooleanField(default=False),
        ),
    ]
